### ISSUE TITLE
Delete functionality doesn't work! 

### ISSUE THREAD

**Issue by BurhanH** [BurhanH/api-app-3#10]
Delete functionality doesn't work as expected. A positive test case is failing!
Check this:

> $ python -m unittest discover tests "*.py" -v
test_create_quote (test_flask.RESTTest) ... ok
test_delete_quote (test_flask.RESTTest) ... [2019-08-28 13:20:01,097] ERROR in app: Exception on /api/v1/quotes/11 [DELETE]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/travis/build/BurhanH/api-app-3/app/api.py", line 61, in delete
    data.QUOTES = [quote for quote in data.QUOTES if quote["quote_id"] != quote_id]
  File "/home/travis/build/BurhanH/api-app-3/app/api.py", line 61, in <listcomp>
    data.QUOTES = [quote for quote in data.QUOTES if quote["quote_id"] != quote_id]
KeyError: 'quote_id'
FAIL
test_edit_quote (test_flask.RESTTest) ... ok
test_get_quote (test_flask.RESTTest) ... ok
test_get_quotes (test_flask.RESTTest) ... ok
======================================================================
FAIL: test_delete_quote (test_flask.RESTTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/BurhanH/api-app-3/tests/test_flask.py", line 39, in test_delete_quote
    self.assertEqual(response.status_code, 200)
AssertionError: 500 != 200
----------------------------------------------------------------------
Ran 5 tests in 0.019s

**Comment by BurhanH** [comment]
Fixed - https://github.com/BurhanH/api-app-3/pull/11
